### ISSUE TITLE
Error when specifying an anonymous volume in singularity compose

### ISSUE THREAD

**Issue by dlevitas** [singularityhub/singularity-compose#66]
I'm attempting to specify a container instance like this:

```
instances:
    mongodb:
        container_name: mongodb
        image: docker://mongo:4.4.15
        platform: linux/amd64
        volumes:
            - /data/db
        ports:
            - 27417:27017 #for local debugging
```

Where I'd like to specify a path inside the container (`/data/db`). Trying this generates the following error:
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/singularity-compose", line 8, in <module>
    sys.exit(start())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/scompose/client/__init__.py", line 277, in start
    main(args=args, parser=parser, extra=extra)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/scompose/client/up.py", line 26, in main
    project.up(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/scompose/project/project.py", line 475, in up
    return self._create(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/scompose/project/project.py", line 539, in _create
    create_func(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/scompose/project/instance.py", line 562, in up
    self.create(writable_tmpfs=writable_tmpfs, ip_address=ip_address)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/scompose/project/instance.py", line 589, in create
    options += self._get_bind_commands()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/scompose/project/instance.py", line 243, in _get_bind_commands
    src, dest = volume.split(":")
ValueError: not enough values to unpack (expected 2, got 1)
```

Which I assume is due to the lack of a colon (`:`). Modifying this to `:/data/db` removes the error and creates a `/data/db` path inside my Singularity container, but the mongodb-associated files are not present. This is a notable difference compared to my docker-compose file build, where the mongodb files are present in a Docker container. 

I was wondering if there's a different way I should be specifying this in my `singularity-compose.yml`?

**Comment by vsoch** [comment]
The volume needs to be a source and destination, and right now you just have the destination. E.g.,:

```
/tmp/hostpath:/data/db
```

**Comment by dlevitas** [comment]
Thanks @vsoch, I suspected that was the underlying issue.

Since I'm trying to translate my `docker-compose.yml` functionality to `singularity-compose.yml`, are these two processes therefore equivalent?

docker-compose:
```
volumes:
    - /data/db
```

singularity-compose:
```
volumes:
    - :/data/db
```

**Comment by vsoch** [comment]
I would always provide a `src:dest`

**Comment by dlevitas** [comment]
Will do, thanks for the clarification
